# These are supported funding model platforms
github: [fab679]

# Optional platforms (uncomment when you actually use them)
# patreon: your-patreon
# open_collective: your-collective
# ko_fi: your-kofi

custom:
  - "https://github.com/sponsors/fab679"
